name: BulkInsert build main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.MicrosoftSQL.BulkInsert/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.MicrosoftSQL.BulkInsert
      prebuild_command: docker-compose up
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}