name: ExecuteQuery build main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.MicrosoftSQL.ExecuteQuery/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.MicrosoftSQL.ExecuteQuery
      env_var_name_1: FRENDS_MICROSOFTSQL_CONNSTRING
      env_var_name_2: FRENDS_MICROSOFTSQL_USERID
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_var_value_1: ${{ secrets.FRENDS_MICROSOFTSQL_CONNSTRING }}
      env_var_value_2: ${{ secrets.FRENDS_MICROSOFTSQL_USERID }}