name: ExecuteProcedure build main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.MicrosoftSQL.ExecuteProcedure/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.MicrosoftSQL.ExecuteProcedure
      prebuild_command: docker-compose -f ./Frends.MicrosoftSQL.ExecuteProcedure.Tests/docker-compose.yml up -d
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}